pull_request_rules:
  - name: Add needs-dco label when DCO check failed
    conditions:
      - or:
        - base=main
        - base=dev
      - -status-success=DCO
    actions:
      label:
        remove:
          - dco-passed
        add:
          - needs-dco

  - name: Add dco-passed label when DCO check passed
    conditions:
      - or:
        - base=main
        - base=dev
      - status-success=DCO
    actions:
      label:
        remove:
          - needs-dco
        add:
          - dco-passed

  # - name: Blocking PR if missing a related issue or PR doesn't have kind/improvement label
  #   conditions:
  #     - base=main
  #     - and:
  #       - -body~=\#[0-9]{1,6}(\s+|$)
  #       - -body~=https://github.com/zilliztech/GPTCache/issues/[0-9]{1,6}(\s+|$)
  #     - -label=kind/improvement
  #     - -title~=\[automated\]
  #   actions:
  #     label:
  #       add:
  #         - do-not-merge/missing-related-issue
  #     comment:
  #       message: |
  #         @{{author}} Please associate the related issue to the body of your Pull Request.  (eg. “issue: #<xyz>”)

  # - name: Dismiss block label if related issue be added into PR
  #   conditions:
  #     - base=main
  #     - or:
  #       - or:
  #         - body~=\#[0-9]{1,6}(\s+|$)
  #         - body~=https://github.com/milvus-io/knowhere/issues/[0-9]{1,6}(\s+|$)
  #       - label=kind/improvement
  #   actions:
  #     label:
  #       remove:
  #         - do-not-merge/missing-related-issue

  - name: Test passed for code changed
    conditions:
      - or:
        - base=main
        - base=dev
      - "status-success=pylint"
      - "status-success=build-pypi"
      - "status-success=unit-test-main"
      - "status-success=codecov/patch"
      - "status-success=codecov/project"
    actions:
      label:
        add:
          - ci-passed

  - name: Test passed for title skip ci
    conditions:
      - or:
        - base=main
        - base=dev
      - title~=\[skip ci\]
      - -files~=^(?=.*((\.(sh|py)|Makefile))).*$
    actions:
      label:
        add:
          - ci-passed

  - name: Test passed for markdown file
    conditions:
      - or:
        - base=main
        - base=dev
      - files=^.*\.md$
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed label when ut failed for main
    conditions:
      - or:
        - base=main
        - base=dev
      - or:
        - "status-success!=pylint"
        - "status-success!=build-pypi"
        - "status-success!=unit-test-main"
      - files~=^(?=.*((\.(sh|py)|Makefile))).*$
    actions:
      label:
        remove:
          - ci-passed