# For `model_src`, `evaluation`, `post_function`, `pre_function`,
# `storage_config` options, Check README for more.

embedding:
    onnx
embedding_config:
    # Set model kws here including `model`, `api_key` if needed
storage_config:
    data_dir:
        gptcache_data
    manager:
        sqlite,faiss
    vector_params:
        # Set vector storage related params here
evaluation: 
    distance
evaluation_config:
    # Set evaluation metric kws here
pre_function:
    get_prompt
post_function:
    first
config:
    similarity_threshold: 0.8
    # Set other config here
