# Configuration File for CodeCov
codecov:
  require_ci_to_pass: no
  notify:
    require_ci_to_pass: no
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 0% #Allow the coverage to drop by threshold%, and posting a success status.
    patch:
      default:
        target: 90%   #target of patch diff
        threshold: 0%
        if_ci_failed: error #success, failure, error, ignore

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches: # branch names that can post comment
    - main
    - dev

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.md"
