name: 🚀 Feature Request
description: As a user, I want to request a feature for GPTCache
title: "[Feature]:"
labels: [kind/feature]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to request a feature for GPTCache! Please fill the form in English!
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A concise description of the problem you are facing or the motivetion behind this feature request.
    placeholder: |
      I faced a problem due to which ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like.
    description: A concise description of the solution for the issue.
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe an alternate solution.
    description: Is there any other approack to solve the problem?
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else? (Additional Context)
    description: |
      Links? References? Anything that will give us more context about this!
  validations:
    required: false