name: Integration test

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'gptcache/**'
      - 'tests/**'
      - '!**.md'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'examples/**'
      - 'gptcache/**'
      - 'tests/**'
      - '!**.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  integration-test-gpt-cache-cli-main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: pip

      - name: Install dependency
        shell: bash
        run: |
          pip install -r requirements.txt

      - name: Build and install
        shell: bash
        run: |
          python setup.py install

      - name: Install test dependency
        shell: bash
        working-directory: tests
        run: |
          pip install -r requirements.txt

      - name: Integration Tests
        timeout-minutes: 10
        shell: bash
        working-directory: tests/integration_tests
        run: |
          python3 -m pytest ./
